import { StateData } from './types';

// Data sourced from EIA (Electricity) and NREL (Solar Irradiance) - 2025 Context
export const US_STATES_DATA: StateData[] = [
  { name: 'Alabama', code: 'AL', avgCostPerKWh: 0.1672, peakSunHours: 4.23 },
  { name: 'Alaska', code: 'AK', avgCostPerKWh: 0.2646, peakSunHours: 3.99 },
  { name: 'Arizona', code: 'AZ', avgCostPerKWh: 0.1555, peakSunHours: 6.57 },
  { name: 'Arkansas', code: 'AR', avgCostPerKWh: 0.1326, peakSunHours: 4.69 },
  { name: 'California', code: 'CA', avgCostPerKWh: 0.3360, peakSunHours: 5.38 },
  { name: 'Colorado', code: 'CO', avgCostPerKWh: 0.1626, peakSunHours: 4.87 },
  { name: 'Connecticut', code: 'CT', avgCostPerKWh: 0.2772, peakSunHours: 3.84 },
  { name: 'Delaware', code: 'DE', avgCostPerKWh: 0.1831, peakSunHours: 4.23 },
  { name: 'District of Columbia', code: 'DC', avgCostPerKWh: 0.2392, peakSunHours: 4.13 },
  { name: 'Florida', code: 'FL', avgCostPerKWh: 0.1570, peakSunHours: 5.67 },
  { name: 'Georgia', code: 'GA', avgCostPerKWh: 0.1453, peakSunHours: 4.74 },
  { name: 'Hawaii', code: 'HI', avgCostPerKWh: 0.3974, peakSunHours: 6.02 },
  { name: 'Idaho', code: 'ID', avgCostPerKWh: 0.1246, peakSunHours: 4.92 },
  { name: 'Illinois', code: 'IL', avgCostPerKWh: 0.1874, peakSunHours: 3.14 },
  { name: 'Indiana', code: 'IN', avgCostPerKWh: 0.1734, peakSunHours: 4.21 },
  { name: 'Iowa', code: 'IA', avgCostPerKWh: 0.1348, peakSunHours: 4.55 },
  { name: 'Kansas', code: 'KS', avgCostPerKWh: 0.1516, peakSunHours: 5.79 },
  { name: 'Kentucky', code: 'KY', avgCostPerKWh: 0.1362, peakSunHours: 4.94 },
  { name: 'Louisiana', code: 'LA', avgCostPerKWh: 0.1239, peakSunHours: 4.92 },
  { name: 'Maine', code: 'ME', avgCostPerKWh: 0.2942, peakSunHours: 4.51 },
  { name: 'Maryland', code: 'MD', avgCostPerKWh: 0.2230, peakSunHours: 4.47 },
  { name: 'Massachusetts', code: 'MA', avgCostPerKWh: 0.3137, peakSunHours: 3.84 },
  { name: 'Michigan', code: 'MI', avgCostPerKWh: 0.2046, peakSunHours: 4.00 },
  { name: 'Minnesota', code: 'MN', avgCostPerKWh: 0.1637, peakSunHours: 4.53 },
  { name: 'Mississippi', code: 'MS', avgCostPerKWh: 0.1447, peakSunHours: 4.44 },
  { name: 'Missouri', code: 'MO', avgCostPerKWh: 0.1295, peakSunHours: 4.73 },
  { name: 'Montana', code: 'MT', avgCostPerKWh: 0.1427, peakSunHours: 4.93 },
  { name: 'Nebraska', code: 'NE', avgCostPerKWh: 0.1313, peakSunHours: 4.79 },
  { name: 'Nevada', code: 'NV', avgCostPerKWh: 0.1377, peakSunHours: 6.41 },
  { name: 'New Hampshire', code: 'NH', avgCostPerKWh: 0.2727, peakSunHours: 4.61 },
  { name: 'New Jersey', code: 'NJ', avgCostPerKWh: 0.2255, peakSunHours: 4.21 },
  { name: 'New Mexico', code: 'NM', avgCostPerKWh: 0.1493, peakSunHours: 6.77 },
  { name: 'New York', code: 'NY', avgCostPerKWh: 0.2695, peakSunHours: 3.79 },
  { name: 'North Carolina', code: 'NC', avgCostPerKWh: 0.1505, peakSunHours: 4.71 },
  { name: 'North Dakota', code: 'ND', avgCostPerKWh: 0.1282, peakSunHours: 5.01 },
  { name: 'Ohio', code: 'OH', avgCostPerKWh: 0.1785, peakSunHours: 4.15 },
  { name: 'Oklahoma', code: 'OK', avgCostPerKWh: 0.1442, peakSunHours: 5.59 },
  { name: 'Oregon', code: 'OR', avgCostPerKWh: 0.1616, peakSunHours: 4.03 },
  { name: 'Pennsylvania', code: 'PA', avgCostPerKWh: 0.2049, peakSunHours: 3.91 },
  { name: 'Rhode Island', code: 'RI', avgCostPerKWh: 0.3116, peakSunHours: 4.23 },
  { name: 'South Carolina', code: 'SC', avgCostPerKWh: 0.1564, peakSunHours: 5.06 },
  { name: 'South Dakota', code: 'SD', avgCostPerKWh: 0.1409, peakSunHours: 5.23 },
  { name: 'Tennessee', code: 'TN', avgCostPerKWh: 0.1306, peakSunHours: 4.45 },
  { name: 'Texas', code: 'TX', avgCostPerKWh: 0.1611, peakSunHours: 4.92 },
  { name: 'Utah', code: 'UT', avgCostPerKWh: 0.1369, peakSunHours: 5.26 },
  { name: 'Vermont', code: 'VT', avgCostPerKWh: 0.2478, peakSunHours: 4.13 },
  { name: 'Virginia', code: 'VA', avgCostPerKWh: 0.1636, peakSunHours: 4.13 },
  { name: 'Washington', code: 'WA', avgCostPerKWh: 0.1406, peakSunHours: 3.57 },
  { name: 'West Virginia', code: 'WV', avgCostPerKWh: 0.1619, peakSunHours: 3.65 },
  { name: 'Wisconsin', code: 'WI', avgCostPerKWh: 0.1837, peakSunHours: 4.29 },
  { name: 'Wyoming', code: 'WY', avgCostPerKWh: 0.1511, peakSunHours: 6.06 },
  { name: 'Puerto Rico', code: 'PR', avgCostPerKWh: 0.2736, peakSunHours: 5.70 }
];

export const COST_PER_WATT = 2.56; // National average cost per watt (residential, pre-tax; NREL data)
export const FEDERAL_TAX_CREDIT_RATE = 0.30; // 30% Inflation Reduction Act
export const DEFAULT_INFLATION_RATE = 4.5; // Projected annual electricity price inflation rate